### ISSUE TITLE
lsd2dsl can't unpack an .lsa file with Spanish characters inside

### ISSUE THREAD

**Issue by camerooncameroon** [nongeneric/lsd2dsl#14]
Hello, thanks for the great tool to unpack dictionary data!

I'm trying to decompile an .lsa file with sounds for Spanish language [PhraseBookRuEs.zip](https://github.com/nongeneric/lsd2dsl/files/5899550/PhraseBookRuEs.zip).
The lsd2dsl popups with an error message saying:

**decompiling of phrasebookrues.lsa failed with error can't open file ¿fuma? wav** 

The decompile process stops at that point, leaving only 12 items extracted (of 934 total).

Can this issue be resolved somehow?

**Comment by nongeneric** [comment]
Hi,

This must be because of the question mark in the name, which is not supported by windows filesystems. I didn't implement any escaping, hence the error.

Maybe you have access to a linux machine? The filesystems there are less finicky when it comes to file names.

Also please note that if you simply want to use this dictionary, then GoldenDict natively supports LSA and doesn't require conversion.

**Comment by camerooncameroon** [comment]
Hi, thanks for the hint to use the linux machine, sure it will help.
I tried to dig into the .lsa to make it work on the android GD, where the sound didn't work. I wanted to repack the audio files to the ...files.zip. Happily, editing the dsl itself helped (had to change the letter-case and it worked).
Thanks again for the wonderful app!
