### ISSUE TITLE
Duden dictionaries conversion issue with missing space characters

### ISSUE THREAD

**Issue by wymmij** [nongeneric/lsd2dsl#18]
First things first - great tool!

This issue is awkward to express because with only the outcome of conversions, there's little for me to go on.

Nevertheless, if you'll bear with me...

When converting a particular Duden dictionary (Das Herkunftswörterbuch), an appreciable number of words in the entries are not separated by a space despite the same (original, unconverted) dictionary being loaded into Duden Bibliothek 5 correctly having the spaces.

Though there is no obvious pattern to such occurrences that leaps out, some words tended to be more commonly affected: for example, 'ist' would often find itself suffixed onto the previous word, so the conversion would produce 'esist' instead of 'es ist'. Other commonly affected words would be short prepositions such as 'aus', or other short but commonly occurring words such as 'auch'. The words often affected aren't _always_ affected either, just to add to the mystery!

I'm assuming that the issue lay with some strange Duden encoding that your parser doesn't know about? I had thought that it may be something like a non-breaking space character, but I've failed to prove that using the Duden Bibliothek 5 software since it happily line-breaks entries on affected words.

Besides, there is another issue that may be related to a non-breaking space and that is that the '~' (tilde) character proliferates all over this conversion and which is used in the DSL format to reproduce the entry's headword. It occurs typically in places you might expect a non-breaking space too, like, erm...for example(!), 'z.~B', which then renders in GoldenDict, if say the headword is 'fordern', as 'z.fordernB'. In this particular case, it was trivial to deal with because a simple regexp could eliminate all tildes.

The non-appearances of spaces where they ought to be also occurs sometimes in other contexts that are at least more easily handled by a few carefully constructed regexps, such as after some full-stops, but, and just to restate the main issue here, regexps only go so far when trying to deal with cases such as no space occurring in, for example, 'Zusammensetzungenhaben'.

Of course, unless you immediately know what the problem is, I guess you'd ideally need access to the dictionary affected, which may pose an issue, so I just thought I'd register this issue nevertheless in the hope that there might be an easy solution.

**Comment by nongeneric** [comment]
Thank you for such a detailed description.

I found the dictionary in question on my PC and sure enough the problems you described are very apparent. It turns out that I misunderstood the meaning of new lines inside articles. Usually an explicit '\\\\' is used for breaking a line and the normal '\n' should be ignored when converting to DSL. For example:

    Anglizismen-Wörterbuch, begr. v. Broder Carstensen. Fortgef. v. Ulrich Busse. 3 Bde. Berlin 1993‒1996.\\
    \\
    Battisti, Carlo / Alessio, Giovanni: Dizionario etimologico italiano. 5 Bde. Neuausgabe Florenz 1975.\\
    \\
    Birkhan, Helmut: Etymologie des Deutschen. Bern 1985.\\
    \\

But when '\n' is used without any '\\\\' nearby, it actually needs to be treated as a whitespace:

    @1mogeln @0@C%ID=16314
    \\
    @8\\
    @9
    (ugs. für:) @0»dem Glück ein bisschen nachhelfen;
    kleine betrügerische Kniffe anwenden«: Die Herkunft des erst seit dem 18.~Jh. bezeugten Verbs
    ist nicht sicher geklärt. Vielleicht handelt es sich um eine Nebenform
    von mdal. \F{_80 80 40}maucheln \F{80 80 40_}@0»heimlich
    oder hinterlistig handeln, betrügen« (vgl. \S{meucheln;:003682289}).@0
    
The distribution of these '\n' breaks seems random and not all articles have them.

As for the tilde -- you are absolutely right. It is indeed used as a non-breaking space that simply needs to be converted to Unicode.

I refactored the newline handling and fixed the tilde. The result looks promising.

I published a [new windows build](https://github.com/nongeneric/lsd2dsl/releases/download/v0.5.3-beta/lsd2dsl-0.5.3-win32.zip) (in case you are not compiling lsd2dsl yourself) and will make a proper hotfix a bit later once I've done more testing.

**Comment by EJamesW** [comment]
Oops. Sorry for the closing and then reopening of the issue! I didn't intend to close it in the first place, but as inexperienced as I am with doing this kind of thing, I clicked "Close with comment" rather than just "Comment", thinking that it meant something like 'stop editing the comment and (presumably) post'.

Nevertheless, I'm happy to close the issue if that's the done thing at this stage? After all, I suppose the list of potential quirks that Duden markup is still yet to reveal could very well remain open for some time!

**Comment by nongeneric** [comment]
rhein. im 13.~Jh. \F{_80 80 40}segere\F{80 80 40_}). \F{~0000FF}Zus.: @4siegreich @0»den Sieg
    errungen habend; oft siegend, erfolgreich« (mhd. \F{_80 80 40}sigerīche\F{80 80 40_}).\F{0000FF~}@0

Well, apparently tag ``\F{~0000FF}`` doesn't mean blue, even though it looks pretty close to ``\F{_00 00 ff}`` that does. I wonder what it's used for then. I see that _sigerīche_ too wasn't meant to be black. I probably need to find a better way of mapping RGB to the limited set of DSL colors.

I think I know what's wrong with the reference. In this case the link, while correct, wasn't resolved by GoldenDict because the parentheses in the heading weren't escaped and so they were treated as DSL variant headings, which they are not. The extra text is supposed to be the "display text" for a link. Duden has this feature, unlike DSL. But I could probably remove it when it's clearly unnecessary.

About building lsd2dsl. I actually had the opposite issue with minizip on Fedora. At some point the old version got replaced with minizip-ng, without changing the package name, while the old version got pushed into another package (without a corresponding mingw32 build, to make things even more annoying). That's why I switched to minizip-ng in the last commit.

And yes, you can extract Duden markup. Though you'll need a debug build (CMAKE_BUILD_TYPE=Debug) for this, as it has a few additional switches enabled. You can call lsd2dsl like this:

    lsd2dsl --bof path-to-bof --idx path-to-idx --duden-utf --out some-dir-path
    
BOF and IDX files together form an archive. There are several of them in a typical dictionary and each contains either text of binary data. For example, my version of Herkunftswoerterbuch dictionary contains its articles in the du7.bof/du7.idx archive. The text itself is not Unicode, but some Duden encoding, that's why I used ``--duden-utf`` to convert it to Unicode. The result is a single "decoded" file containing the whole archive.

Also, I don't see any reason to close this issue. While it's true that Duden has plenty of quirks for sure and a perfect conversion might be a long way off, I still think that fixing at least the most glaring issues is worth it. So I appreciate your reporting them. Thanks.

I will try to fix the issues you found in a few days.

**Comment by nongeneric** [comment]
I've made a few changes to reference handling, there should be less duplicate text in parentheses next to an article reference. Also, the altogether broken references should now be fixed.

The unexpected text color will go away, though unless Duden text color maps exactly to one of the standard colors, the text will remain black for now.

**Comment by nongeneric** [comment]
Well, making an IDX/BOF archive is easy: BOF consists of deflated blocks and IDX stores their offsets. The headings (HIC) though are quite a bit more complicated, and I haven't done enough reverse engineering to be able to recreate them. The headings sometimes contain some information that lsd2dsl loses along the way.

Anyway, here's a python script to create IDX/BOF:

    import zlib
    import struct

    def deflate(data):
        obj = zlib.compressobj(
            0,
            zlib.DEFLATED,
            -zlib.MAX_WBITS,
            zlib.DEF_MEM_LEVEL,
            0)
        return obj.compress(data) + obj.flush()

    def inflate(data):
        obj = zlib.decompressobj(-zlib.MAX_WBITS)
        return obj.decompress(data) + obj.flush()

    input_path = '/tmp/decoded.dump'
    idx_path = '/tmp/test.idx'
    bof_path = '/tmp/test.bof'

    block_size = 8192

    input = open(input_path, 'rb').read()
    input_len = len(input)

    bof = bytearray()
    idx = bytearray()

    pos = 0
    while True:
        block = input[pos:pos+block_size]
        if len(block) == 0:
            break
        pos += block_size
        idx += struct.pack('<I', len(bof))
        bof += deflate(block)
        
    idx += struct.pack('<I', len(bof))
    idx += struct.pack('<I', len(bof))
    idx += struct.pack('<I', input_len)

    open(idx_path, 'wb').write(idx)
    open(bof_path, 'wb').write(bof)
    
I used zero compression to work around Duden's use of custom compression tables. I explained them in [a blog](https://rcebits.com/rce/2020/01/14/duden.html) if you are interested.

Please note that articles are referenced from HIC by absolute offsets into the decoded file, so changing the length of an article will destroy all the articles that follow it.

**Comment by EJamesW** [comment]
Perfect! That works superbly. Thank you so much!

And since I'm only wanting to explore Duden's formatting for exploratory purposes, that the absolute offsets from the HIC will no longer be correct for articles that follow any article-length-altering edits is no problem - although, would it be naive to think that the offsets for each article that follows any edit couldn't just be updated to reflect the new offsets? I mean, if I know I've added 21 bytes to an article, couldn't I just add 21 to each number greater than whatever the offset is of the edited article? I suppose the cross-references would have to be updated too.
